apiVersion: v1
kind: Namespace
metadata:
  name: seccomp-agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: seccomp-agent
  namespace: seccomp-agent
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: seccomp-agent
subjects:
- kind: ServiceAccount
  name: seccomp-agent
  namespace: seccomp-agent
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seccomp-agent
  namespace: seccomp-agent
  labels:
    k8s-app: seccomp-agent
spec:
  selector:
    matchLabels:
      k8s-app: seccomp-agent
  template:
    metadata:
      labels:
        k8s-app: seccomp-agent
    spec:
      serviceAccount: seccomp-agent
      hostPID: true
      containers:
      - name: seccomp-agent
        image: local-registry:5000/seccomp-agent
        imagePullPolicy: Always
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
          capabilities:
            add:
            - "SYS_PTRACE"
            - "SYS_ADMIN"
            - "NET_ADMIN"
        volumeMounts:
        - name: seccomp-policies
          mountPath: /host/seccomp
        - name: run
          mountPath: /run
        - name: cgroup
          mountPath: /sys/fs/cgroup
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: seccomp-policies
        hostPath:
          path: /var/lib/kubelet/seccomp
      - name: run
        hostPath:
          path: /run
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
